# Generated by Django 2.2.13 on 2023-07-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_submittaskattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittaskattempt',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
