# Generated by Django 2.2.13 on 2023-07-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_submittaskattempt_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittaskattempt',
            name='success',
        ),
    ]
