SYNONYMS = {
  "auth": ["oauth", "login", "signin"],
  "users": ["user", "users", "employee", "employees", "account", "accounts", "member", "members", "staff", "people"],
  "projects": ["task", "tasks", "subprojects", "subproject"],
  "organizations": ["organization", "institution", "company", "companies", "groups"],
  "integrations": ["connection", "connections", "setup", "setups"],
  "last_activity": ["activity", "activities", "action", "actions", "last"],
  "members": ["staff_member", "staff_members", "persons", "users"],
  "links": ["integrations", "connectivity"],
  "activities": ["activity", "actions", "action", "operations", "operation", "work", "working"],
  "applications": ["application", "app", "apps"],
  "urls": ["url", "link", "links"],
  "screenshots": ["shots", "screens", "images"],
  "notes": ["memos", "data"],
  "tasks": ["todos", "task"],
  "weekly": ["by_week", "week", "weeks", "seven_days"],
  "my": ["own", "me", "myself", "i"],
  "team": ["members", "team_members", "staff"],
  "custom": ["specific", "advanced"],
  "by_project": ["projects", "group_by_project", "project"],
  "by_member": ["members", "member", "group_by_member"],
  "by_date": ["date", "dates", "days", "day", "daily"],
  "time_edit_logs": ["time_logs", "edit_logs"],
  "team_payments": ["earnings", "money"]
}
